---
staging:
  debug: &debug true
  mysql:
    bi_alerts:
      user: *std_user
      password: *std_pass
      db: ""
      host: *std_host
      tablename: ''
  slack:
    endpoint: ""
    username: ""
  mozmail:
    endpoint: ""
    access_id: ""
    secret: ""
    email_type: "no_template"
    from_user_id: ""
  templates:
    path: "./templates/"
    extension: ".jinja"
prod:
  debug: *debug
  mysql: # Maintain your list of connections here
    example_db:
      user: &std_user ""
      password: &std_pass ""
      db: ""
      host: &std_host ""
    bi_alerts:
      user: *std_user
      password: *std_pass
      db: ""
      host: *std_host
      tablename: ''
  slack:
    endpoint: ""
    username: ""
  mozmail:
    endpoint: ""
    access_id: ""
    secret: ""
    email_type: "no_template"
    from_user_id: ""
  templates:
    path: "./templates/"
    extension: ".jinja"